# Chapter key {.unnumbered}

::: {.callout-note title="Learning outcomes" collapse=false}
Every chapter starts with the "Learning outcomes",
which describe what you will learn from this chapter.
To make these learning outcomes more useful to you as a reader,
we have expanded them to include a summary of the "solution" for each outcome,
instead of just stating what you are to learn in the chapter.

For example,
instead of simply stating:
"Explain the main advantage of visualizing data instead"
we would write:
"Explain that the main advantage of visualizing data instead of presenting it with numbers is that they are easier to interpret for humans.

As such,
the learning objectives also serve as the summary of each chapter.
:::

## A heading

The main text will go here.
This can cover both practical
and theoretical aspects of data visualization.

### A sub-heading

These will be used to divide content further.

## Exercises

::::: {.callout-default .ex-prompt}

Exercises aim to engage you actively with the material,
both to make it more fun to learn
and to improve your learning.
Try to solve the exercise on your own first,
before looking at the hint and the solution;
this active engagement is what aids your learning.
Click the hint below to expand it.

:::: {.callout-default .ex-hint}

Before looking at the solution,
try to use the hint to figure out the answer.

::: {.callout-default .ex-solution}

The solution is inside the "Hint" section,
to encourage you to first try to use the hint to solve the exercise.

:::

::::

:::::

## Coding content

Coding content will often include a panel with multiple tabs,
so that you can easily see what the same code looks like
for different visualization packages.
These sections also include explanations
that are specific to the code of a certain package,
rather than being about data visualization in general.

::: {.panel-tabset}

### Package One

```{python}
# Code for the first package, e.g.:
range(5)

```

### Package Two

```{r}
# Code for the second package, e.g.:
seq(5)
```

:::

::: {.column-margin}

**Optional content**

Content in the margin is optional
and can include
fun factual tidbits,
historical explanations,
etymology,
and more.

:::

## Deep dive

<details><summary>Click to expand the optional deep dive or proceed to the exercise mission.</summary>

Every chapter contains a deep dive
with optional content.
This section elaborates on a concept that was learned in the chapter,
and often contains more challenging content.

</details>

## Exercise mission

In addition to the exercises spread throughout the content,
each chapter contains a set of connected exercises in the end
that interweaves the content learned throughout the chapter.
This challenges you to deepen your understanding
as it requires comprehension of how the content fit together
rather than solely mastering each section in isolation.

To help you along the way on these exercises,
you will be able to converse with an avatar from the fictional setting of the book.
These will make it clear what your goal is for each section
and help you along the way if you get stuck.

Before you get started with this section,
make sure you review the chapter summary
in the learning outcomes
and that you understand each of the items there.
