project:
  type: book

book:
  title: "Textbook"
  author: "Norah Jones"
  date: "7/29/2024"
  chapters:
    - index.qmd
    - chapter_1.qmd
    - summary.qmd

filters:
  - custom-callouts.lua

format:
  html:
    theme: cosmo
    css: styles.css
