project:
  type: book

book:
  title: "Data Visualization"
  # author: "Norah Jones"
  date: today
  chapters:
    - index.qmd
    - 0_chapter-key.qmd
    - 1_intro.qmd
    - 2_grouping.qmd

filters:
  - custom-callouts.lua

format:
  live-html:
    theme: cosmo
    css: styles.css
    monofont: "Ubuntu Mono"
    mainfont: Ubuntu
    number-depth: 2
webr:
  packages:
    - dplyr
    - readr
    - ggplot2