project:
  type: book

book:
  title: "Data Visualization"
  # author: "Norah Jones"
  date: today
  chapters:
    - index.qmd
    - 0_chapter-key.qmd
    - 1_why-visualize-data.qmd
    - 2_grammar-of-graphics.qmd
    - 3_individual-observations.qmd
    - 4_magnitude.qmd
    - 5_groups.qmd
    - 6_trends.qmd
    - 7_statistical-summaries.qmd
    - 8_distributions.qmd
    - 9_multiple-distributions.qmd
    - 99_misc.qmd

filters:
  - custom-callouts.lua

format:
  live-html:
    theme: cosmo
    css: styles.css
    monofont: "Ubuntu Mono"
    mainfont: Ubuntu
    number-depth: 2
    tbl-cap-location: bottom

execute:
  cache: true
