project:
  type: book

book:
  title: "Data Visualization"
  # author: "Norah Jones"
  date: today
  chapters:
    - index.qmd
    - chapter-key.qmd
    - chapter_1.qmd
    - chapter_2.qmd

filters:
  - custom-callouts.lua

format:
  html:
    theme: cosmo
    css: styles.css
