name: "Rebuild and deploy PR and diff versions of a website to gh-pages branch"

# YOUR_FILES below should be replaced with a list of files that, when changed in a PR, will trigger the PR deploy preview
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'textbook/**'
    branches:
      - 'main'

jobs:
  deploy-pr-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        extra-packages: |
          any::ggplot2
          any::rcmdcheck
